export const AVERAGE_MEASUREMENTS_REQUEST = "AVERAGE_MEASUREMENTS_REQUEST";
export const AVERAGE_MEASUREMENTS_SUCCESS = "AVERAGE_MEASUREMENTS_SUCCESS";
export const AVERAGE_MEASUREMENTS_FAILURE = "AVERAGE_MEASUREMENTS_FAILURE";

export const MEASUREMENTS_LOAD_REQUEST = "MEASUREMENTS_LOAD_REQUEST";
export const MEASUREMENTS_LOAD_SUCCESS = "MEASUREMENTS_LOAD_SUCCESS";
export const MEASUREMENTS_LOAD_FAILURE = "MEASUREMENTS_LOAD_FAILURE";

